[[bin]]
name = "temp_tracker"
path = "src/bin/day1/temp_tracker.rs"

[[bin]]
name = "greetings"
path = "src/bin/day1/greetings.rs"

[[bin]]
name = "constants"
path = "src/bin/day2/constants.rs"


[package]
name = "rust-workspace"
version = "0.1.0"
edition = "2024"

[dependencies]
